---
apiVersion: v1
kind: Pod
metadata:
  name: wipeshared
spec:
  restartPolicy: "Never"
  volumes: 
  - name: shared
    hostPath:
      path: /tmp
        
  containers:
  - name: wipeshared
    image: ibmblockchain/fabric-tools:1.0.0
    imagePullPolicy: Always
    command: ["sh", "-c", "rm -rf /shared/*"]
    volumeMounts:
    - mountPath: /shared
      name: shared